version: '3.8'

services:
  java:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - "./trivia_application-0.0.1-SNAPSHOT.jar:/app.jar"

  vue:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - 8081:8080
